stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  KUBECONFIG_PATH: "/builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/.kube/config"
  HELM_CHART_DIR: "helm"
  DOCKER_IMAGE: "sergeiprokaev/django-app"
  DEFAULT_TAG: "latest" # Резервный тег

build:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  script:
    - |
      IMAGE_TAG=${CI_COMMIT_TAG:-$DEFAULT_TAG}
      echo "Using tag: $IMAGE_TAG"
      # Входим в Docker Registry
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
      # Собираем Docker-образ
      docker build -t $DOCKER_IMAGE:$IMAGE_TAG .
      # Загружаем образ в Docker Registry
      docker push $DOCKER_IMAGE:$IMAGE_TAG
  only:
    - branches

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  before_script:
    - sh -c "mkdir -p $(dirname $KUBECONFIG_PATH)"
    - sh -c "echo \"$KUBECONFIG\" > $KUBECONFIG_PATH"
    - sh -c "kubectl get nodes"
  script:
    - |
      IMAGE_TAG=${CI_COMMIT_TAG:-$DEFAULT_TAG}
      echo "Using tag: $IMAGE_TAG"
      kubectl create namespace default || true
      helm upgrade --install django-app $HELM_CHART_DIR \
        --namespace default \
        --set image.repository=$DOCKER_IMAGE \
        --set image.tag=$IMAGE_TAG \
        --wait
  only:
    - branches
