replicaCount: 1

image:
  repository: registry.example.com/your-group/django-app
  tag: "latest"

service:
  type: ClusterIP
  port: 8000

postgresql:
  image: postgres:14
  username: django
  password: secretpassword
  database: django

persistence:
  enabled: true
  size: 10Gi
