image:
  repository: sergeiprokaev/django-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3003  # Порт, на котором работает ваше приложение

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: banka.life
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - banka.life
      secretName: banka-life-tls

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: "vinhle"
        password: "password"
        database: "tutorial-dev"
  persistence:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce