replicaCount: 1

image:
  repository: sergeiprokaev/django-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: banka.life
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: banka-life-tls
      hosts:
        - banka.life


resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

postgres:
  enabled: true
  image: postgres:15
  username: django
  password: django_password
  database: django_db
