apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host | default "banka.life" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django-app
                port:
                  number: {{ .Values.service.port }}
  tls:
    - hosts:
        - {{ (index .Values.ingress.hosts 0).host | default "banka.life" }}
      secretName: {{ (index .Values.ingress.tls 0).secretName | default "default-tls-secret" }}
