apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "django-app.fullname" . }}-postgres-pvc
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}